bot:
  token: ""
  # not functional yet 
  allowedIds: ["1312313", "1312313"]

  status:
    # messages go in order from first -> last
    messages: ["shit", "raided by .gg/invite etc etc"]


  raid:
    #messages to send to each channel created
    messages: ["raided by me", "raided =)"]
    # delay * time.Millisecond 
    messageDelay: 200

    guildEdit:
      enable: true
      names: ["shit server", "Server 123"]
      delay: 1
    
    channels:
      names: ['neekeri', 'tussuhuora', 'fallen-society', 'yleinen', 'media', 'announcements']
      amount: 20
      edit:
        enabled: true
        delay: 4000

    roles:
      enable: true
      names: ['Role', 'a faggot was here', 'Admin', 'Owner', 'Moderator']
      amount: 100
      delay: 1