bot:
  token: ""
  allowedIds: ["123123"]

  status:
    # messages go in order from first -> last
    messages: ["educational purpose by ametysti xD"]

  raid:
    # delay * time.Millisecond
    messageDelay: 100
    guildEditDelay: 2000
    channelEditDelay: 4000

    channels:
     name: 'neekeri'
     amount: 30

    messages: ["test", "this", "on", "your", "servers", "only"]